# Generated by Django 3.1.2 on 2020-10-29 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=32)),
                ('group_desc', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_number', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=30)),
                ('user_grade', models.CharField(max_length=10)),
                ('user_dept', models.CharField(max_length=45)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_password', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('meeting_id', models.AutoField(primary_key=True, serialize=False)),
                ('meeting_open_data', models.DateTimeField(auto_now_add=True)),
                ('meeting_link', models.CharField(max_length=256)),
                ('open_user_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voracay.user')),
            ],
        ),
        migrations.CreateModel(
            name='LogMettingChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_chat_url', models.CharField(max_length=256)),
                ('meeting_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voracay.meeting')),
            ],
        ),
        migrations.CreateModel(
            name='LogMeetingUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voracay.meeting')),
                ('user_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voracay.user')),
            ],
        ),
        migrations.CreateModel(
            name='LogCall',
            fields=[
                ('call_id', models.AutoField(primary_key=True, serialize=False)),
                ('call_start_time', models.DateTimeField(auto_now_add=True)),
                ('call_end_time', models.DateTimeField()),
                ('caller_user_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voracay.user')),
            ],
        ),
        migrations.CreateModel(
            name='GroupManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voracay.group')),
                ('user_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voracay.user')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='group_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voracay.user'),
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favor_user_number', models.IntegerField()),
                ('user_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voracay.user')),
            ],
        ),
    ]
