# Generated by Django 3.1.2 on 2020-10-29 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voracay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogCallUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voracay.logcall')),
                ('user_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voracay.user')),
            ],
        ),
    ]
