# Generated by Django 3.1.2 on 2020-10-30 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voracay', '0004_auto_20201030_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_email',
            field=models.EmailField(max_length=128),
        ),
    ]
